---
title: "Enunciados Trabajo"
author: "Carmen Mora"
date: "2023-10-22"
output: pdf_document
---

**Carmen Mora García**

*Problema 1*

Aplicar los criterios de decisión bajo incertidumbre a una matriz de datos 
generados aleatoriamente, considerandolos primero beneficios y luego costos:


*Problema 2*

Un fabricante de cojines estudia lanzar un nuevo modelo al mercado, debatiendose entre
cuatro estampados distintos. Los estampados candidatos son: lisos, con plantas, 
con frases y con figuras geometricas. Los beneficios esperados (expresados 
en millones de euros) en el año siguiente al lanzamiento en función del tipo de 
interés al consumo son:
             E1    E2    E3    E4
Lisos        30    26    13    19
Plantas      25    17    10    28
Frases       22    25    21    16
Fig. Geom.   24    18    23    27
¿Cuál sería la opción que recomendaría a la empresa?

**Miguel Maldonado Sampayo**

*Problema 1*

El primer problema a resolver es la siguiente tabla de decisión:
```{r echo=FALSE}
source("teoriadecision_funciones_incertidumbre.R")
tabla=crea.tablaX(c(3,7,25,10,6,2,12,11,5),3,3)
rownames(tabla)=c("d1","d2","d3")
colnames(tabla)=c("e1","e2","e3")
tabla
```


*Problema 2*

Un grupo de 5 amigos quiere decidir a que hotel viajar de vacaciones para el viaje han ido a una agencia de viaje donde les han dado varias opciones:

- La primera opción es la que les costaría 70€ la noche por persona pero a partir de la tercera noche son 50€, pero sería con alojamiento y desayuno solamente.

- La segunda opción es la que le costaría 55€ la noche por persona para reservas de 3 noches o mas, serían 60€ para reservas de menos de 3 noches, en este caso en régimen de solo alojamiento.

- La última opción es la que les costaría 100€ la noche por persona en pensión completa (alojamiento + desayuno, comida y cena) sin ninguna opcion de descuento u oferta.

Coste por desayuno fuera del hotel por persona: 7€.

Coste por comida fuera del hotel por persona: 15€.

Tienen dos opciones ir de viernes a  domingo (2 noches) o ir de miércoles a domingo (4 noches), pero no lo saben todavia porque depende de que le den dias libres en el trabajo a un par de ellos, pero tienen que hacer la reserva ya para que no les suba el precio. Por tanto, teniendo en cuenta que hacen el check in a las 13:00pm en el hotel y el check out a las 12:00pm, ¿Que opción es mas recomendable para este grupo de amigos si pretenden minimizar los costes?